// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/utils"
)

// DeployVolume - an object describing a volume to deploy
type DeployVolume struct {
	InstanceID *string `json:"instance_id,omitempty"`
	// Datacenter Location
	LocationCode *LocationCode `default:"FIN-01" json:"location_code"`
	Name         string        `json:"name"`
	Size         float64       `json:"size"`
	// storage volume type
	Type VolumeType `json:"type"`
}

func (d DeployVolume) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeployVolume) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DeployVolume) GetInstanceID() *string {
	if o == nil {
		return nil
	}
	return o.InstanceID
}

func (o *DeployVolume) GetLocationCode() *LocationCode {
	if o == nil {
		return nil
	}
	return o.LocationCode
}

func (o *DeployVolume) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DeployVolume) GetSize() float64 {
	if o == nil {
		return 0.0
	}
	return o.Size
}

func (o *DeployVolume) GetType() VolumeType {
	if o == nil {
		return VolumeType("")
	}
	return o.Type
}
