// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/utils"
)

// Location - An object describing a location
type Location struct {
	// Datacenter Location
	Code        *LocationCode `default:"FIN-01" json:"code"`
	CountryCode *string       `json:"country_code,omitempty"`
	Name        *string       `json:"name,omitempty"`
}

func (l Location) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *Location) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Location) GetCode() *LocationCode {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *Location) GetCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.CountryCode
}

func (o *Location) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
