// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// LocationCode - Datacenter Location
type LocationCode string

const (
	LocationCodeFin01 LocationCode = "FIN-01"
)

func (e LocationCode) ToPointer() *LocationCode {
	return &e
}

func (e *LocationCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FIN-01":
		*e = LocationCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LocationCode: %v", v)
	}
}
