// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/utils"
)

type LocationAvailabilities struct {
	Availabilites []InstanceType `json:"availabilites,omitempty"`
	// Datacenter Location
	LocationCode *LocationCode `default:"FIN-01" json:"location_code"`
}

func (l LocationAvailabilities) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LocationAvailabilities) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *LocationAvailabilities) GetAvailabilites() []InstanceType {
	if o == nil {
		return nil
	}
	return o.Availabilites
}

func (o *LocationAvailabilities) GetLocationCode() *LocationCode {
	if o == nil {
		return nil
	}
	return o.LocationCode
}
