// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// StartupScript - startup script object
type StartupScript struct {
	// startup script id. you need to first add a startup script to datacrunch via the startup script endpoint
	ID *string `json:"id,omitempty"`
	// name of the startup script
	Name string `json:"name"`
	// the startup script text
	Script string `json:"script"`
}

func (o *StartupScript) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *StartupScript) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *StartupScript) GetScript() string {
	if o == nil {
		return ""
	}
	return o.Script
}
