// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/utils"
)

// UserBalance - The user's balance
type UserBalance struct {
	Amount float64 `json:"amount"`
	// currency type
	Currency *Currency `default:"usd" json:"currency"`
}

func (u UserBalance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserBalance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UserBalance) GetAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Amount
}

func (o *UserBalance) GetCurrency() *Currency {
	if o == nil {
		return nil
	}
	return o.Currency
}
