// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/utils"
	"time"
)

// Volume - Storage volume details object
type Volume struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// id of a storage volume
	ID         string  `json:"id"`
	InstanceID *string `json:"instance_id"`
	IsOsVolume bool    `json:"is_os_volume"`
	// Datacenter Location
	LocationCode *LocationCode `default:"FIN-01" json:"location_code"`
	Name         string        `json:"name"`
	Size         float64       `json:"size"`
	SSHKeyIds    []interface{} `json:"ssh_key_ids,omitempty"`
	// status of a storage volume
	Status VolumeStatus `json:"status"`
	Target *string      `json:"target,omitempty"`
	// storage volume type
	Type VolumeType `json:"type"`
}

func (v Volume) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *Volume) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Volume) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Volume) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Volume) GetInstanceID() *string {
	if o == nil {
		return nil
	}
	return o.InstanceID
}

func (o *Volume) GetIsOsVolume() bool {
	if o == nil {
		return false
	}
	return o.IsOsVolume
}

func (o *Volume) GetLocationCode() *LocationCode {
	if o == nil {
		return nil
	}
	return o.LocationCode
}

func (o *Volume) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Volume) GetSize() float64 {
	if o == nil {
		return 0.0
	}
	return o.Size
}

func (o *Volume) GetSSHKeyIds() []interface{} {
	if o == nil {
		return nil
	}
	return o.SSHKeyIds
}

func (o *Volume) GetStatus() VolumeStatus {
	if o == nil {
		return VolumeStatus("")
	}
	return o.Status
}

func (o *Volume) GetTarget() *string {
	if o == nil {
		return nil
	}
	return o.Target
}

func (o *Volume) GetType() VolumeType {
	if o == nil {
		return VolumeType("")
	}
	return o.Type
}
