// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/utils"
)

type Price struct {
	// currency type
	Currency           *Currency `default:"usd" json:"currency"`
	PricePerMonthPerGb *float64  `json:"price_per_month_per_gb,omitempty"`
}

func (p Price) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Price) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Price) GetCurrency() *Currency {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *Price) GetPricePerMonthPerGb() *float64 {
	if o == nil {
		return nil
	}
	return o.PricePerMonthPerGb
}

// VolumeTypeDetails - storage volume type details
type VolumeTypeDetails struct {
	Price *Price `json:"price,omitempty"`
	// storage volume type
	Type *VolumeType `json:"type,omitempty"`
}

func (o *VolumeTypeDetails) GetPrice() *Price {
	if o == nil {
		return nil
	}
	return o.Price
}

func (o *VolumeTypeDetails) GetType() *VolumeType {
	if o == nil {
		return nil
	}
	return o.Type
}
