// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// VolumeStatus - status of a storage volume
type VolumeStatus string

const (
	VolumeStatusAttached VolumeStatus = "attached"
	VolumeStatusDetached VolumeStatus = "detached"
	VolumeStatusDeleted  VolumeStatus = "deleted"
	VolumeStatusOrdered  VolumeStatus = "ordered"
	VolumeStatusCreating VolumeStatus = "creating"
	VolumeStatusDeleting VolumeStatus = "deleting"
)

func (e VolumeStatus) ToPointer() *VolumeStatus {
	return &e
}

func (e *VolumeStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "attached":
		fallthrough
	case "detached":
		fallthrough
	case "deleted":
		fallthrough
	case "ordered":
		fallthrough
	case "creating":
		fallthrough
	case "deleting":
		*e = VolumeStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VolumeStatus: %v", v)
	}
}
