// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// VolumeType - storage volume type
type VolumeType string

const (
	VolumeTypeNvMe VolumeType = "NVMe"
	VolumeTypeHdd  VolumeType = "HDD"
)

func (e VolumeType) ToPointer() *VolumeType {
	return &e
}

func (e *VolumeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NVMe":
		fallthrough
	case "HDD":
		*e = VolumeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VolumeType: %v", v)
	}
}
