// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// AddScriptsRequestBody - a startup script object
type AddScriptsRequestBody struct {
	// script name
	Name string `json:"name"`
	// bash script content
	Script string `json:"script"`
}

func (o *AddScriptsRequestBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AddScriptsRequestBody) GetScript() string {
	if o == nil {
		return ""
	}
	return o.Script
}

type AddScriptsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// startup script added successfully, return id of the new script
	StartupScriptID *string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AddScriptsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddScriptsResponse) GetStartupScriptID() *string {
	if o == nil {
		return nil
	}
	return o.StartupScriptID
}

func (o *AddScriptsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddScriptsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
