// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteSSHKeyByIDRequest struct {
	SSHKeyID string `pathParam:"style=simple,explode=false,name=sshKeyId"`
}

func (o *DeleteSSHKeyByIDRequest) GetSSHKeyID() string {
	if o == nil {
		return ""
	}
	return o.SSHKeyID
}

type DeleteSSHKeyByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteSSHKeyByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteSSHKeyByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteSSHKeyByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
