// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAllVolumesRequest struct {
	// Return all user storage volumes with specific status
	Status *string `queryParam:"style=form,explode=true,name=status"`
}

func (o *GetAllVolumesRequest) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllVolumesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Returns an array of all the user's storage volumes
	Volumes []shared.Volume
}

func (o *GetAllVolumesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllVolumesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllVolumesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllVolumesResponse) GetVolumes() []shared.Volume {
	if o == nil {
		return nil
	}
	return o.Volumes
}
