// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAvailabilityRequest struct {
	// The type of the instance to check
	InstanceType shared.InstanceType `pathParam:"style=simple,explode=false,name=instanceType"`
	// Check if the given instance type is available for spot instance (true) or on-demand (false - default)
	IsSpot *bool `queryParam:"style=form,explode=true,name=isSpot"`
	// Check for availability in a specific location
	LocationCode *string `queryParam:"style=form,explode=true,name=locationCode"`
}

func (o *GetAvailabilityRequest) GetInstanceType() shared.InstanceType {
	if o == nil {
		return shared.InstanceType("")
	}
	return o.InstanceType
}

func (o *GetAvailabilityRequest) GetIsSpot() *bool {
	if o == nil {
		return nil
	}
	return o.IsSpot
}

func (o *GetAvailabilityRequest) GetLocationCode() *string {
	if o == nil {
		return nil
	}
	return o.LocationCode
}

type GetAvailabilityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Return instance type availability - true or false
	Boolean *bool
}

func (o *GetAvailabilityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAvailabilityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAvailabilityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAvailabilityResponse) GetBoolean() *bool {
	if o == nil {
		return nil
	}
	return o.Boolean
}
