// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAvailabilityDeprecatedRequest struct {
	// The type of the instance to check
	InstanceType shared.InstanceType `pathParam:"style=simple,explode=false,name=instanceType"`
}

func (o *GetAvailabilityDeprecatedRequest) GetInstanceType() shared.InstanceType {
	if o == nil {
		return shared.InstanceType("")
	}
	return o.InstanceType
}

type GetAvailabilityDeprecatedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Return instance type availability - true or false
	Boolean *bool
}

func (o *GetAvailabilityDeprecatedResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAvailabilityDeprecatedResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAvailabilityDeprecatedResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAvailabilityDeprecatedResponse) GetBoolean() *bool {
	if o == nil {
		return nil
	}
	return o.Boolean
}
