// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAllAvailabilityRequest struct {
	// Check if the given instance type is available for spot instance (true) or on-demand (false - default)
	IsSpot *bool `queryParam:"style=form,explode=true,name=isSpot"`
	// Check for availability in a specific location
	LocationCode *string `queryParam:"style=form,explode=true,name=locationCode"`
}

func (o *GetAllAvailabilityRequest) GetIsSpot() *bool {
	if o == nil {
		return nil
	}
	return o.IsSpot
}

func (o *GetAllAvailabilityRequest) GetLocationCode() *string {
	if o == nil {
		return nil
	}
	return o.LocationCode
}

type GetAllAvailabilityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// An array of all the available instance types for each location
	Classes []shared.LocationAvailabilities
}

func (o *GetAllAvailabilityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllAvailabilityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllAvailabilityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllAvailabilityResponse) GetClasses() []shared.LocationAvailabilities {
	if o == nil {
		return nil
	}
	return o.Classes
}
