// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAllInstancesRequest struct {
	// Return all user instances with specific status
	Status *shared.InstanceStatus `queryParam:"style=form,explode=true,name=status"`
}

func (o *GetAllInstancesRequest) GetStatus() *shared.InstanceStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllInstancesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Returns an array of all the user's instances
	Instances []shared.Instance
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAllInstancesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllInstancesResponse) GetInstances() []shared.Instance {
	if o == nil {
		return nil
	}
	return o.Instances
}

func (o *GetAllInstancesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllInstancesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
