// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetSSHKeyByIDRequest struct {
	SSHKeyID string `pathParam:"style=simple,explode=false,name=sshKeyId"`
}

func (o *GetSSHKeyByIDRequest) GetSSHKeyID() string {
	if o == nil {
		return ""
	}
	return o.SSHKeyID
}

type GetSSHKeyByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ssh key found, return key details
	SSHKey *shared.SSHKey
}

func (o *GetSSHKeyByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSSHKeyByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSSHKeyByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSSHKeyByIDResponse) GetSSHKey() *shared.SSHKey {
	if o == nil {
		return nil
	}
	return o.SSHKey
}
