// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetScriptByIDRequest struct {
	ScriptID string `pathParam:"style=simple,explode=false,name=scriptId"`
}

func (o *GetScriptByIDRequest) GetScriptID() string {
	if o == nil {
		return ""
	}
	return o.ScriptID
}

type GetScriptByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// startup script object
	StartupScript *shared.StartupScript
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetScriptByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetScriptByIDResponse) GetStartupScript() *shared.StartupScript {
	if o == nil {
		return nil
	}
	return o.StartupScript
}

func (o *GetScriptByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetScriptByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
