// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetVolumeByIDRequest struct {
	// volume id
	VolumeID interface{} `pathParam:"style=simple,explode=false,name=volumeId"`
}

func (o *GetVolumeByIDRequest) GetVolumeID() interface{} {
	if o == nil {
		return nil
	}
	return o.VolumeID
}

type GetVolumeByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Volume details
	Volume *shared.Volume
}

func (o *GetVolumeByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetVolumeByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetVolumeByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetVolumeByIDResponse) GetVolume() *shared.Volume {
	if o == nil {
		return nil
	}
	return o.Volume
}
