// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"errors"
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/models/shared"
	"github.com/squat/terraform-provider-datacrunch/internal/sdk/pkg/utils"
	"net/http"
)

type InstanceActionDeprecatedIDType string

const (
	InstanceActionDeprecatedIDTypeStr        InstanceActionDeprecatedIDType = "str"
	InstanceActionDeprecatedIDTypeArrayOfstr InstanceActionDeprecatedIDType = "arrayOfstr"
)

type InstanceActionDeprecatedID struct {
	Str        *string
	ArrayOfstr []string

	Type InstanceActionDeprecatedIDType
}

func CreateInstanceActionDeprecatedIDStr(str string) InstanceActionDeprecatedID {
	typ := InstanceActionDeprecatedIDTypeStr

	return InstanceActionDeprecatedID{
		Str:  &str,
		Type: typ,
	}
}

func CreateInstanceActionDeprecatedIDArrayOfstr(arrayOfstr []string) InstanceActionDeprecatedID {
	typ := InstanceActionDeprecatedIDTypeArrayOfstr

	return InstanceActionDeprecatedID{
		ArrayOfstr: arrayOfstr,
		Type:       typ,
	}
}

func (u *InstanceActionDeprecatedID) UnmarshalJSON(data []byte) error {

	str := new(string)
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = str
		u.Type = InstanceActionDeprecatedIDTypeStr
		return nil
	}

	arrayOfstr := []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfstr, "", true, true); err == nil {
		u.ArrayOfstr = arrayOfstr
		u.Type = InstanceActionDeprecatedIDTypeArrayOfstr
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u InstanceActionDeprecatedID) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfstr != nil {
		return utils.MarshalJSON(u.ArrayOfstr, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// InstanceActionDeprecatedRequestBody - id of instances to perform the action on, and the action type
type InstanceActionDeprecatedRequestBody struct {
	Action shared.ActionType          `json:"action"`
	ID     InstanceActionDeprecatedID `json:"id"`
	// array of storage volume ids
	VolumeIds []string `json:"volume_ids,omitempty"`
}

func (o *InstanceActionDeprecatedRequestBody) GetAction() shared.ActionType {
	if o == nil {
		return shared.ActionType("")
	}
	return o.Action
}

func (o *InstanceActionDeprecatedRequestBody) GetID() InstanceActionDeprecatedID {
	if o == nil {
		return InstanceActionDeprecatedID{}
	}
	return o.ID
}

func (o *InstanceActionDeprecatedRequestBody) GetVolumeIds() []string {
	if o == nil {
		return nil
	}
	return o.VolumeIds
}

type InstanceActionDeprecatedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *InstanceActionDeprecatedResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *InstanceActionDeprecatedResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *InstanceActionDeprecatedResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
